// <auto-generated />
using System;
using CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD.Migrations
{
    [DbContext(typeof(DuomenuKontekstas))]
    [Migration("20230618091231_darbuotojuPacientai")]
    partial class darbuotojuPacientai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD.Models.Darbuotojas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GimimoData")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statusas")
                        .HasColumnType("int");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Darbuotojai");
                });

            modelBuilder.Entity("CRUD.Models.Pacientas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GimimoData")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pacientai");
                });

            modelBuilder.Entity("CRUD.Models.Pareiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pareigos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pareigos");
                });

            modelBuilder.Entity("DarbuotojasPacientas", b =>
                {
                    b.Property<int>("DarbuotojaiId")
                        .HasColumnType("int");

                    b.Property<int>("PacientaiId")
                        .HasColumnType("int");

                    b.HasKey("DarbuotojaiId", "PacientaiId");

                    b.HasIndex("PacientaiId");

                    b.ToTable("DarbuotojuPacientai", (string)null);
                });

            modelBuilder.Entity("DarbuotojasPareiga", b =>
                {
                    b.Property<int>("DarbuotojaiId")
                        .HasColumnType("int");

                    b.Property<int>("PareigosId")
                        .HasColumnType("int");

                    b.HasKey("DarbuotojaiId", "PareigosId");

                    b.HasIndex("PareigosId");

                    b.ToTable("DarbuotojuPareigos", (string)null);
                });

            modelBuilder.Entity("DarbuotojasPacientas", b =>
                {
                    b.HasOne("CRUD.Models.Darbuotojas", null)
                        .WithMany()
                        .HasForeignKey("DarbuotojaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD.Models.Pacientas", null)
                        .WithMany()
                        .HasForeignKey("PacientaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarbuotojasPareiga", b =>
                {
                    b.HasOne("CRUD.Models.Darbuotojas", null)
                        .WithMany()
                        .HasForeignKey("DarbuotojaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD.Models.Pareiga", null)
                        .WithMany()
                        .HasForeignKey("PareigosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
